routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::group(['prefix'=>'admin','namespace'=>'Admin'], function(){
	Route::resource('/posts', 'PostsController');
	Route::resource('/cat', 'CategoriesController');
});

app/Albom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Albom extends Model
{
    protected $fillable = ['title', 'descr', 'date'];
	
	public function category()
	{
		return $this->belongTo(Albom::class);
	}
	
	public function posts()
	{
		return $this->hasMany(Post::class);
	}
}

app/Basket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Basket extends Model
{
    public function posts()
	{
		return $this->belongsToMany(
			'basket_post',
			'user_id',
			'post_id'
		);
	}
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title', 'descr', 'price'];
	
	public function alboms()
	{
		return $this->hasMany(Albom::class);
	}
	
	public static function add($fields)
	{
		$category = new static;
		$category->fill($fields);
		$category->save();
		return $category;
	}
	
	public function edit($fields)
	{		
		$this->fill($fields);
		$this->save();		
	}

	public function remove()
	{		
		//очистить категория->альбомы->посты
		$this->delete();
	}
	
	public function getTitle()
	{
		return $this->title;
	}

	public function getPrice()
	{
		return $this->price;
	}
	
}

app/Post.php
<?php

namespace App;

use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	const PHOTO_PATH_BIG = ''
	const PHOTO_PATH_SMALL = ''
	
    protected $fillable = ['image'];
	
	public function albom()
	{
		return $this->belongTo(Albom::class);
	}
	
	public function baskets()
	{
		return $this->belongsToMany(
			'basket_post',
			'post_id',
			'user_id'
		);
	}
	
	private function cleanup()
	{
		if ($this->image) !- null)
		{
			Storage::delete('uploads/photo_big/' . $this->image);	
			Storage::delete('uploads/photo_small/' . $this->image);
		}			
	}
	
	public static function add($fields)
	{
		$post = new static;
		$post->fill($fields);
		$post->user_id = 1;		
		$post->save();
		return $post;
	}
	
	public function edit($fields)
	{		
		$this->fill($fields);		
		$this->save();		
	}

	public function remove()
	{		
		$this->cleanup();
		$this->delete();		
	}
	
	public function getBigImage()
	{
		return $this->image == null ? '/img/no-image.png': 'uploads/photo_big/' . $this->image;
	}
	
	public function getSmallImage()
	{
		return $this->image == null ? '/img/no-image.png': 'uploads/photo_small/' . $this->image;
	}
	
}

app/Purchase.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Category;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$categories = Category::all();
    	return view('admin.categories.index', ['categories'	=>	$categories]);    
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {		
    	return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //return env('TEST', false);
		//return config('app.name');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/categories/create.blade.php
@extends('admin.layout')

@section('page-header')
	<h1>Категории<small>Создание</small></h1>
@endsection

@section('content')
	<!-- Default box -->
	<div class="box">
		{!! Form::open(['route' => 'categories.store']) !!}
		<div class="box-header with-border">
			<h3 class="box-title">Добавляем категорию</h3> @include('admin.errors')
		</div>
		<div class="box-body">
			<div class="col-md-6">
				<div class="form-group">
					<label for="exampleInputEmail1">Название</label>
					<input type="text" class="form-control" id="exampleInputEmail1" placeholder="" name="title">
				</div>
			</div>
		</div>
		<!-- /.box-body -->
		<div class="box-footer">
			<button class="btn btn-default">Назад</button>
			<button class="btn btn-success pull-right">Добавить</button>
		</div>
		<!-- /.box-footer-->
		{!! Form::close() !!}
	</div>
	<!-- /.box -->
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layout')

@section('page-header')
	<h1>Привет! Это админка<small>Категории</small></h1>
@endsection

@section('content')
	<!-- Default box -->
	<div class="box">
		<div class="box-header">
			<h3 class="box-title">Листинг сущности</h3>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			<div class="form-group">
				<a href="{{route('cat.create')}}" class="btn btn-success">Добавить</a>
			</div>
			<table id="example1" class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>ID</th>
						<th>Название</th>
						<th>Описание</th>
						<th>Цена</th>
						<th>Действия</th>
					</tr>
				</thead>
				<tbody>
					@foreach($categories as $category)
					<tr>
						<td>{{$category->id}}</td>
						<td>{{$category->title}}</td>
						<td>
							<a href="{{--route('categories.edit', $category->id)--}}" class="fa fa-pencil"></a>

							{{Form::open(['route'=>['categories.destroy', $category->id], 'method'=>'delete'])}}
							<button onclick="return confirm('are you sure?')" type="submit" class="delete">
								<i class="fa fa-remove"></i>
							</button>

							{{Form::close()}}

						</td>
					</tr>
					@endforeach
				</tbody>
					<tr>
						<th>ID</th>
						<th>Название</th>
						<th>Описание</th>
						<th>Цена</th>
						<th>Действия</th>
					</tr>				
				<tfoot>
				</tfoot>
			</table>
		</div>
		<!-- /.box-body -->
	</div>
@endsection

resources/views/admin/errors.blade.php
@if ($errors->any())
    <div class="container">
    	<div class="row">
    		<div class="col-md-10">
    			<div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
    		</div>
    	</div>
    </div>
@endif

resources/views/admin/head.blade.php
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{{ asset('assets/bootstrap/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('assets/font-awesome/4.5.0/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('assets/ionicons/2.0.1/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('assets/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('assets/dist/css/skins/_all-skins.min.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Blank Page</title>
	@include('admin.head')
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

		@include('admin.main-header')

        <!-- Left side column. contains the sidebar -->
		@include('admin.sidebar-left')
        
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
				@yield('page-header')
				
				@include('admin.errors')
            </section>

            <!-- Main content -->
            <section class="content">
					@yield('content')
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
		
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.3.7
            </div>
            <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com/">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>

    </div><!-- ./wrapper -->
	@include('admin.scripts')
</body>

</html>

resources/views/admin/main-header.blade.php
        <header class="main-header">
            <!-- Logo -->
            <a href="../../index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>A</b>LT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b>LTE</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </nav>
        </header>

resources/views/admin/scripts.blade.php
    <!-- jQuery 2.2.3 -->
    <script src="{{ asset('assets/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="{{ asset('assets/bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- SlimScroll -->
    <script src="{{ asset('assets/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets/plugins/fastclick/fastclick.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('assets/dist/js/app.min.js') }}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('assets/dist/js/demo.js') }}"></script>

resources/views/admin/sidebar-left.blade.php
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="https://via.placeholder.com/160" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>Alexander Pierce</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
					<li><a href="#"><i class="fa fa-list-ul"></i> <span>Категории</span></a></li>
                    <!--li><a href="#"><i class="fa fa-sticky-note-o"></i> <span>Посты</span></a></li>                    
                    <li><a href="#"><i class="fa fa-tags"></i> <span>Теги</span></a></li>
                    <li>
                        <a href="#">
                            <i class="fa fa-commenting"></i> <span>Комментарии</span>
                            <span class="pull-right-container"><small class="label pull-right bg-green">5</small></span>
                        </a>
                    </li>
                    <li><a href="#"><i class="fa fa-users"></i> <span>Пользователи</span></a></li>
                    <li><a href="#"><i class="fa fa-user-plus"></i> <span>Подписчики</span></a></li-->

                </ul>
            </section>            
        </aside>